### ISSUE TITLE
job.stop() says a job has already been stopped on the first call to stop method

### ISSUE THREAD

**Issue by caleb-johnson** [Qiskit-Extensions/quantum-serverless#860] opened 2023-08-04 12:49 UTC
When I call `job.stop` on a running remote program, I get an error saying "Job was already not running", even though it was running, the `status` reported 'RUNNING', and it was the first time I called `stop`.

[Relevant code](https://github.com/Qiskit-Extensions/quantum-serverless/blob/039f62f23d54ca3a1c18bdedadbf70deb9458fdc/gateway/api/views.py#L135).

I believe these couple lines of code should have a slightly different logic.

I was spinning up distributed tasks from within my remote program, which may or may not factor into this behavior.

**Comment by psschwei** [comment] 2023-08-04 13:30
Actually, if you're on the cluster, we can probably pull the logs from there...

**Comment by caleb-johnson** [comment] 2023-08-04 13:32
> Actually, if you're on the cluster, we can probably pull the logs from there...

Any job I manually `stop`ped had this behavior, so you could pull any of those

**Comment by IceKhan13** [comment] 2023-08-04 14:35
https://github.com/Qiskit-Extensions/quantum-serverless/blob/main/gateway/api/views.py#L135

**Comment by caleb-johnson** [comment] 2023-08-06 15:26
It seems the logic in our source code is correct. It seems ray is saying the job wasn't running, according to [ray docs](https://docs.ray.io/en/latest/cluster/running-applications/job-submission/doc/ray.job_submission.JobSubmissionClient.stop_job.html#ray.job_submission.JobSubmissionClient.stop_job).

This seems like a ray bug. Will try to reproduce on a simpler script. I'll write an infinite-loop script which runs in the head node, and I'll call `stop` on it. If we see this behavior in that scenario, I believe it's fair to say it is a Ray bug.

**Comment by akihikokuroda** [comment] 2023-09-20 16:46
@caleb-johnson I tried this but I couldn't reproduce now.  Some code have been changed including #873.  Would you check if you still see this issue?

**Comment by caleb-johnson** [comment] 2023-09-20 17:55
> @caleb-johnson I tried this but I couldn't reproduce now. Some code have been changed including #873. Would you check if you still see this issue?

Yes, I will try again. I did not notice a bug in the code, and it was not clear to me why results would not be deserialized in the client. I was hoping #873 might resolve this as well. Will test soon and let you know, thanks!!

**Comment by IceKhan13** [comment] 2023-10-03 19:45
Closing as it looks like it is no longer an issue.

**Closed by IceKhan13** 2023-10-03 19:45 UTC
Labels: bug, good first issue
